# Generated by Django 5.2.4 on 2025-11-03 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("perfis", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome da Categoria"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("receita", "Receita"), ("despesa", "Despesa")],
                        max_length=50,
                        verbose_name="Tipo da Categoria",
                    ),
                ),
                (
                    "fazenda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorias",
                        to="perfis.fazenda",
                        verbose_name="Fazenda",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categorias",
                "ordering": ["nome"],
                "unique_together": {("nome", "tipo", "fazenda")},
            },
        ),
        migrations.CreateModel(
            name="Movimentacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("parcelas", models.IntegerField(default=1)),
                (
                    "imposto_renda",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        verbose_name="Imposto de Renda [Sim/Não]",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                ("data", models.DateField(verbose_name="Data da Movimentação")),
                (
                    "cadastrado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Cadastrado Em"
                    ),
                ),
                (
                    "cadastrada_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cadastrado Por",
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movimentacao.categoria",
                        verbose_name="Categoria da Movimentação",
                    ),
                ),
                (
                    "fazenda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="perfis.fazenda",
                        verbose_name="Fazenda",
                    ),
                ),
                (
                    "parceiros",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="perfis.parceiros",
                        verbose_name="Empresa Parceira",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Movimentações",
                "ordering": ["-cadastrado_em"],
            },
        ),
        migrations.CreateModel(
            name="Parcela",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordem_parcela", models.IntegerField(verbose_name="Ordem da Parcela")),
                (
                    "valor_parcela",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor da Parcela"
                    ),
                ),
                (
                    "data_vencimento",
                    models.DateField(verbose_name="Data de Vencimento"),
                ),
                (
                    "valor_pago",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Valor Pago",
                    ),
                ),
                (
                    "status_pagamento",
                    models.CharField(
                        choices=[("Pendente", "Pendente"), ("Pago", "Pago")],
                        default="Pendente",
                        max_length=50,
                        verbose_name="Status do Pagamento",
                    ),
                ),
                (
                    "data_quitacao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Quitação"
                    ),
                ),
                (
                    "movimentacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movimentacao.movimentacao",
                        verbose_name="Movimentação",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="movimentacao",
            index=models.Index(fields=["-data"], name="movimentaca_data_15bef8_idx"),
        ),
        migrations.AddIndex(
            model_name="movimentacao",
            index=models.Index(
                fields=["categoria", "-data"], name="movimentaca_categor_f46ba8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movimentacao",
            index=models.Index(
                fields=["fazenda", "-data"], name="movimentaca_fazenda_cc2749_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="parcela",
            index=models.Index(
                fields=["-data_vencimento"], name="movimentaca_data_ve_b00045_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="parcela",
            index=models.Index(
                fields=["status_pagamento", "-data_vencimento"],
                name="movimentaca_status__4f34cd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="parcela",
            index=models.Index(
                fields=["movimentacao", "ordem_parcela"],
                name="movimentaca_movimen_0eda13_idx",
            ),
        ),
    ]
