# Generated by Django 5.2.4 on 2025-10-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movimentacao", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movimentacao",
            name="imposto_renda",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Imposto de Renda [Sim/Não]"
            ),
        ),
    ]
