# Generated by Django 5.2.4 on 2025-11-03 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movimentacao", "0002_alter_movimentacao_imposto_renda"),
        ("perfis", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="movimentacao",
            unique_together={("categoria", "parceiros", "data", "fazenda")},
        ),
        migrations.RemoveField(
            model_name="movimentacao",
            name="tipo",
        ),
    ]
