# Generated by Django 5.2.4 on 2025-11-03 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movimentacao", "0003_alter_movimentacao_unique_together_and_more"),
        ("perfis", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="movimentacao",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="movimentacao",
            name="parceiros",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="perfis.parceiros",
                verbose_name="Empresa Parceira",
            ),
        ),
    ]
