# Generated by Django 5.2.4 on 2025-11-03 15:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movimentacao", "0004_alter_movimentacao_unique_together_and_more"),
        ("perfis", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="movimentacao",
            index=models.Index(fields=["-data"], name="movimentaca_data_15bef8_idx"),
        ),
        migrations.AddIndex(
            model_name="movimentacao",
            index=models.Index(
                fields=["categoria", "-data"], name="movimentaca_categor_f46ba8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movimentacao",
            index=models.Index(
                fields=["fazenda", "-data"], name="movimentaca_fazenda_cc2749_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="parcela",
            index=models.Index(
                fields=["-data_vencimento"], name="movimentaca_data_ve_b00045_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="parcela",
            index=models.Index(
                fields=["status_pagamento", "-data_vencimento"],
                name="movimentaca_status__4f34cd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="parcela",
            index=models.Index(
                fields=["movimentacao", "ordem_parcela"],
                name="movimentaca_movimen_0eda13_idx",
            ),
        ),
    ]
