# Generated by Django 5.2.4 on 2025-11-03 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Fazenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome da Fazenda"),
                ),
                (
                    "cidade",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Cidade"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        blank=True, max_length=2, null=True, verbose_name="Estado (UF)"
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "ativa",
                    models.BooleanField(default=True, verbose_name="Fazenda Ativa"),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "dono",
                    models.ForeignKey(
                        help_text="Produtor responsável pela fazenda",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fazendas_proprietario",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Proprietário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fazenda",
                "verbose_name_plural": "Fazendas",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("produtor", "Produtor"),
                            ("funcionario", "Funcionário"),
                        ],
                        default="funcionario",
                        max_length=20,
                        verbose_name="Tipo de Usuário",
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="Telefone"
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        blank=True,
                        max_length=14,
                        null=True,
                        unique=True,
                        verbose_name="CPF",
                    ),
                ),
                (
                    "data_nascimento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Nascimento"
                    ),
                ),
                (
                    "fazendas",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Fazendas que este usuário pode acessar",
                        related_name="usuarios",
                        to="perfis.fazenda",
                        verbose_name="Fazendas com Acesso",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Usuário",
                "verbose_name_plural": "Perfis de Usuários",
                "ordering": ["user__first_name", "user__username"],
            },
        ),
        migrations.CreateModel(
            name="Parceiros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100, verbose_name="Nome da Empresa Parceira"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="Telefone"
                    ),
                ),
                (
                    "if_adicionais",
                    models.TextField(
                        blank=True, null=True, verbose_name="Informações Adicionais"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="E-mail"
                    ),
                ),
                (
                    "fazenda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parceiros",
                        to="perfis.fazenda",
                        verbose_name="Fazenda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parceiro",
                "verbose_name_plural": "Parceiros",
                "ordering": ["nome"],
                "unique_together": {("nome", "fazenda")},
            },
        ),
    ]
