# Generated by Django 5.2.4 on 2025-11-03 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("perfis", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100, verbose_name="Nome do Medicamento"
                    ),
                ),
                (
                    "fazenda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="perfis.fazenda",
                        verbose_name="Fazenda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medicamento",
                "verbose_name_plural": "Medicamentos",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="EntradaMedicamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_medicamento",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor Total"
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(verbose_name="Quantidade Adicionada"),
                ),
                (
                    "quantidade_disponivel",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Quantidade atual disponível (descontando saídas)",
                        verbose_name="Quantidade Disponível",
                    ),
                ),
                ("validade", models.DateField(verbose_name="Data de Validade")),
                (
                    "data_cadastro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Cadastro"
                    ),
                ),
                (
                    "observacao",
                    models.TextField(blank=True, null=True, verbose_name="Observação"),
                ),
                (
                    "cadastrada_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cadastrado Por",
                    ),
                ),
                (
                    "medicamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medicamento.medicamento",
                        verbose_name="Medicamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrada de Medicamento",
                "verbose_name_plural": "Entradas de Medicamentos",
                "ordering": ["validade"],
            },
        ),
        migrations.CreateModel(
            name="SaidaMedicamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(verbose_name="Quantidade Removida"),
                ),
                (
                    "motivo",
                    models.TextField(
                        blank=True, null=True, verbose_name="Motivo da Saída"
                    ),
                ),
                (
                    "data_saida",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Saída"
                    ),
                ),
                (
                    "entrada",
                    models.ForeignKey(
                        help_text="Entrada da qual foi dada a saída",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medicamento.entradamedicamento",
                        verbose_name="Entrada Origem",
                    ),
                ),
                (
                    "medicamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medicamento.medicamento",
                        verbose_name="Medicamento",
                    ),
                ),
                (
                    "registrada_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado Por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Saída de Medicamento",
                "verbose_name_plural": "Saídas de Medicamentos",
                "ordering": ["-data_saida"],
            },
        ),
        migrations.AddIndex(
            model_name="entradamedicamento",
            index=models.Index(
                fields=["validade"], name="medicamento_validad_7cd097_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entradamedicamento",
            index=models.Index(
                fields=["validade", "quantidade_disponivel"],
                name="medicamento_validad_7a4993_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="entradamedicamento",
            index=models.Index(
                fields=["medicamento", "validade"],
                name="medicamento_medicam_a4f2a7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="entradamedicamento",
            index=models.Index(
                fields=["-data_cadastro"], name="medicamento_data_ca_936f2b_idx"
            ),
        ),
    ]
