# Generated by Django 5.2.4 on 2025-11-03 15:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicamento", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="entradamedicamento",
            index=models.Index(
                fields=["validade"], name="medicamento_validad_7cd097_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entradamedicamento",
            index=models.Index(
                fields=["validade", "quantidade_disponivel"],
                name="medicamento_validad_7a4993_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="entradamedicamento",
            index=models.Index(
                fields=["medicamento", "validade"],
                name="medicamento_medicam_a4f2a7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="entradamedicamento",
            index=models.Index(
                fields=["-data_cadastro"], name="medicamento_data_ca_936f2b_idx"
            ),
        ),
    ]
