# Generated by Django 5.2.4 on 2025-11-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicamento", "0001_initial"),
        ("perfis", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="medicamento",
            unique_together={("nome", "fazenda")},
        ),
        migrations.AddIndex(
            model_name="medicamento",
            index=models.Index(
                fields=["fazenda", "nome"], name="medicamento_fazenda_f647f6_idx"
            ),
        ),
    ]
